# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/microblaze1/microblaze1.srcs/sources_1/bd/microblaze1/ip/microblaze1_dlmb_bram_if_cntlr_0/microblaze1_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'microblaze1_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/microblaze1/microblaze1.gen/sources_1/bd/microblaze1/ip/microblaze1_dlmb_bram_if_cntlr_0/microblaze1_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze1_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/microblaze1/microblaze1.srcs/sources_1/bd/microblaze1/ip/microblaze1_dlmb_bram_if_cntlr_0/microblaze1_dlmb_bram_if_cntlr_0.xci
# IP: The module: 'microblaze1_dlmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/microblaze1/microblaze1.gen/sources_1/bd/microblaze1/ip/microblaze1_dlmb_bram_if_cntlr_0/microblaze1_dlmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze1_dlmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
