set_property SRC_FILE_INFO {cfile:c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/colorPMODipTest/colorPMODipTest.gen/sources_1/bd/colorPMODipTest/ip/colorPMODipTest_PmodCOLOR_0_0/colorPMODipTest_PmodCOLOR_0_0_board.xdc rfile:../../../colorPMODipTest.gen/sources_1/bd/colorPMODipTest/ip/colorPMODipTest_PmodCOLOR_0_0/colorPMODipTest_PmodCOLOR_0_0_board.xdc id:1 order:EARLY used_in_board:yes scoped_inst:inst prop_thru_buffer:yes} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JB7} [get_ports Pmod_out_pin7_t]
set_property src_info {type:SCOPED_XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JB8} [get_ports Pmod_out_pin8_t]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JB9} [get_ports Pmod_out_pin9_t]
set_property src_info {type:SCOPED_XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property BOARD_PIN {JB10} [get_ports Pmod_out_pin10_t]
