# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/steph/Downloads/digilent-xdc-master/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/colorPMODipTest/colorPMODipTest.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest || ORIG_REF_NAME==colorPMODipTest} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_microblaze_0_0/colorPMODipTest_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_microblaze_0_0 || ORIG_REF_NAME==colorPMODipTest_microblaze_0_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_clk_wiz_0_0/colorPMODipTest_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_clk_wiz_0_0 || ORIG_REF_NAME==colorPMODipTest_clk_wiz_0_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_dlmb_v10_0/colorPMODipTest_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_dlmb_v10_0 || ORIG_REF_NAME==colorPMODipTest_dlmb_v10_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_ilmb_v10_0/colorPMODipTest_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_ilmb_v10_0 || ORIG_REF_NAME==colorPMODipTest_ilmb_v10_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_dlmb_bram_if_cntlr_0/colorPMODipTest_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==colorPMODipTest_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_ilmb_bram_if_cntlr_0/colorPMODipTest_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==colorPMODipTest_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_lmb_bram_0/colorPMODipTest_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_lmb_bram_0 || ORIG_REF_NAME==colorPMODipTest_lmb_bram_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_xbar_0/colorPMODipTest_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_xbar_0 || ORIG_REF_NAME==colorPMODipTest_xbar_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_microblaze_0_axi_periph_0/colorPMODipTest_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_microblaze_0_axi_periph_0 || ORIG_REF_NAME==colorPMODipTest_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_microblaze_0_axi_intc_0/colorPMODipTest_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_microblaze_0_axi_intc_0 || ORIG_REF_NAME==colorPMODipTest_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_microblaze_0_xlconcat_0/colorPMODipTest_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_microblaze_0_xlconcat_0 || ORIG_REF_NAME==colorPMODipTest_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_mdm_1_0/colorPMODipTest_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_mdm_1_0 || ORIG_REF_NAME==colorPMODipTest_mdm_1_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_rst_clk_wiz_0_100M_0/colorPMODipTest_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==colorPMODipTest_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_axi_uartlite_0_0/colorPMODipTest_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_axi_uartlite_0_0 || ORIG_REF_NAME==colorPMODipTest_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_PmodCOLOR_0_0/colorPMODipTest_PmodCOLOR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_PmodCOLOR_0_0 || ORIG_REF_NAME==colorPMODipTest_PmodCOLOR_0_0} -quiet] -quiet

# IP: bd/colorPMODipTest/ip/colorPMODipTest_axi_gpio_0_0/colorPMODipTest_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==colorPMODipTest_axi_gpio_0_0 || ORIG_REF_NAME==colorPMODipTest_axi_gpio_0_0} -quiet] -quiet

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/colorPMODipTest/colorPMODipTest.gen/sources_1/bd/colorPMODipTest/colorPMODipTest_ooc.xdc
