# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/testIPI2/testIPI2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2 || ORIG_REF_NAME==testIPI2} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_axi_gpio_0_0/testIPI2_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_axi_gpio_0_0 || ORIG_REF_NAME==testIPI2_axi_gpio_0_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_axi_gpio_1_0/testIPI2_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_axi_gpio_1_0 || ORIG_REF_NAME==testIPI2_axi_gpio_1_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_clk_wiz_0_0/testIPI2_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_clk_wiz_0_0 || ORIG_REF_NAME==testIPI2_clk_wiz_0_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_axi_uartlite_0_0/testIPI2_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_axi_uartlite_0_0 || ORIG_REF_NAME==testIPI2_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_reset_inv_0_0/testIPI2_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_reset_inv_0_0 || ORIG_REF_NAME==testIPI2_reset_inv_0_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_microblaze_0_0/testIPI2_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_microblaze_0_0 || ORIG_REF_NAME==testIPI2_microblaze_0_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_dlmb_v10_0/testIPI2_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_dlmb_v10_0 || ORIG_REF_NAME==testIPI2_dlmb_v10_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_ilmb_v10_0/testIPI2_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_ilmb_v10_0 || ORIG_REF_NAME==testIPI2_ilmb_v10_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_dlmb_bram_if_cntlr_0/testIPI2_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==testIPI2_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_ilmb_bram_if_cntlr_0/testIPI2_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==testIPI2_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_lmb_bram_0/testIPI2_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_lmb_bram_0 || ORIG_REF_NAME==testIPI2_lmb_bram_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_mdm_1_0/testIPI2_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_mdm_1_0 || ORIG_REF_NAME==testIPI2_mdm_1_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_rst_clk_wiz_0_100M_0/testIPI2_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==testIPI2_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_xbar_0/testIPI2_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_xbar_0 || ORIG_REF_NAME==testIPI2_xbar_0} -quiet] -quiet

# IP: bd/testIPI2/ip/testIPI2_microblaze_0_axi_periph_0/testIPI2_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==testIPI2_microblaze_0_axi_periph_0 || ORIG_REF_NAME==testIPI2_microblaze_0_axi_periph_0} -quiet] -quiet

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/testIPI2/testIPI2/testIPI2.gen/sources_1/bd/testIPI2/testIPI2_ooc.xdc
