# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/digilent-xdc-master/Basys-3-Master.xdc

# Block Designs: bd/microblaze1/microblaze1.bd
# Block Designs: The module: 'microblaze1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/microblaze1/ip/microblaze1_clk_wiz_0_0/microblaze1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_clk_wiz_0_0 || ORIG_REF_NAME==microblaze1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_microblaze_0_0/microblaze1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_microblaze_0_0 || ORIG_REF_NAME==microblaze1_microblaze_0_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_dlmb_v10_0/microblaze1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_dlmb_v10_0 || ORIG_REF_NAME==microblaze1_dlmb_v10_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_ilmb_v10_0/microblaze1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_ilmb_v10_0 || ORIG_REF_NAME==microblaze1_ilmb_v10_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_dlmb_bram_if_cntlr_0/microblaze1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_ilmb_bram_if_cntlr_0/microblaze1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==microblaze1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_lmb_bram_0/microblaze1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_lmb_bram_0 || ORIG_REF_NAME==microblaze1_lmb_bram_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_xbar_0/microblaze1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_xbar_0 || ORIG_REF_NAME==microblaze1_xbar_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_microblaze_0_axi_periph_0/microblaze1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==microblaze1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_microblaze_0_axi_intc_0/microblaze1_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_microblaze_0_axi_intc_0 || ORIG_REF_NAME==microblaze1_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_microblaze_0_xlconcat_0/microblaze1_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_microblaze_0_xlconcat_0 || ORIG_REF_NAME==microblaze1_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_mdm_1_0/microblaze1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_mdm_1_0 || ORIG_REF_NAME==microblaze1_mdm_1_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_rst_clk_wiz_0_100M_0/microblaze1_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==microblaze1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_axi_uartlite_0_0/microblaze1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_axi_uartlite_0_0 || ORIG_REF_NAME==microblaze1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_axi_gpio_0_0/microblaze1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_axi_gpio_0_0 || ORIG_REF_NAME==microblaze1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_axi_gpio_0_2/microblaze1_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_axi_gpio_0_2 || ORIG_REF_NAME==microblaze1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/microblaze1/ip/microblaze1_PmodCOLOR_0_1/microblaze1_PmodCOLOR_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==microblaze1_PmodCOLOR_0_1 || ORIG_REF_NAME==microblaze1_PmodCOLOR_0_1} -quiet] -quiet

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/microblaze1/microblaze1.gen/sources_1/bd/microblaze1/microblaze1_ooc.xdc
