# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/colorPMODipTest/colorPMODipTest.srcs/sources_1/bd/colorPMODipTest/ip/colorPMODipTest_lmb_bram_0/colorPMODipTest_lmb_bram_0.xci
# IP: The module: 'colorPMODipTest_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/colorPMODipTest/colorPMODipTest.gen/sources_1/bd/colorPMODipTest/ip/colorPMODipTest_lmb_bram_0/colorPMODipTest_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'colorPMODipTest_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/colorPMODipTest/colorPMODipTest.srcs/sources_1/bd/colorPMODipTest/ip/colorPMODipTest_lmb_bram_0/colorPMODipTest_lmb_bram_0.xci
# IP: The module: 'colorPMODipTest_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/steph/OneDrive/Desktop/School/ProjectLab1/microblaze1/colorPMODipTest/colorPMODipTest.gen/sources_1/bd/colorPMODipTest/ip/colorPMODipTest_lmb_bram_0/colorPMODipTest_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'colorPMODipTest_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
